### ISSUE TITLE
scene_manager.py Loop

### ISSUE THREAD

**Issue by bennoben** [TheGentlemanOctopus/oracle#10]
Need to figure out the most efficient way of keeping the main manager from running all the time. Do we semaphore? Go to sleep?
This is a continuation of the discussion taken place in #8

**Comment by bennoben** [comment]
@afishman I've been thinking about this and I think we should go down the mutex and sleep() route.
Does the scene_manager.py main loop only update the channels that have been changed each loop?

**Comment by afishman** [comment]
Yeah it only updates devices which have something in their queue - and then dumps the whole lot onto opc

**Comment by afishman** [comment]
do you want to have a go at this? I wouldn't mind fleshing out some of the geometry layouts (panels/cubes), I have written this sort of code before
